source "https://rubygems.org"

gem "rails", "~> 7.2.3", ">= 7.2.3.1"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# API
gem "rack-cors"

# 認証
gem "bcrypt", "~> 3.1.7"
gem "jwt"

# 商品検索
gem "pg_search"
gem "neighbor"  # pgvector for Rails

# サブスク決済
gem "stripe"

# AI連携 (Dify)
gem "faraday"
gem "faraday-retry"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "dotenv-rails"
end
