default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "postgres" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "app" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "app_password" } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "app_development" } %>

test:
  <<: *default
  database: app_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
